title: Commonhaus Foundation
description: > # this means to ignore newlines until the next tag
  The Commonhaus Foundation is dedicated to nurturing and sustaining GitHub-style
  open-source projects through community-driven collaboration and shared stewardship.
  We unite developers, contributors, and users in a dynamic ecosystem, focusing on
  the long-term growth and stability of essential open-source libraries and frameworks
  without the overhead of traditional governance models.
disableLiveReload: true
disablePathToLower: true
frontmatter:
  date:
    - :git
    - :default
languageCode: en-us
publishDir: "../public"
uglyURLs: true
enableGitInfo: true
outputs:
  home:
    - HTML
    - RSS
    - JSON
params:
  render_hooks:
    link:
      errorLevel: 'warning'
markup:
  defaultMarkdownHandler: goldmark
module:
  mounts:
  - source: ../foundation/bylaws/README.md
    target: content/bylaws/_index.md
  - source: ../foundation/bylaws
    includeFiles: '*.md'
    target: content/bylaws
  - source: ../foundation/policies/README.md
    target: content/policies/_index.md
  - source: ../foundation/policies
    includeFiles: '*.md'
    target: content/policies
  - source: content
    target: content
  - source: ../foundation/
    includeFiles: '*.yaml'
    target: data