name: update-vote-results

on:
  schedule:
    - cron: '47 3,17 * * *'

  workflow_dispatch:

permissions: {}

jobs:
  process_votes:
    concurrency:
      group: generated_content
    permissions:
      contents: write
    uses: commonhaus/vote-record-actions/.github/workflows/receive-votes.yml@main
    with:
      repositories: "commonhaus/foundation"
      target_dir: "site/_generated/votes"
      branch: "main"
    secrets: inherit

  update:
    needs: process_votes
    if: needs.process_votes.outputs.votes_updated
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - name: Push GH Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run -R commonhaus/commonhaus.github.io gh-pages.yml